export const URL_PATHS = {
  DASHBOARD: "/dashboard",
  MARKETS: "/markets",
  MACHINES: "/machines",
  OPERATORS: "/operators",
  PRODUCTS: "/products",
  TRANSACTIONS: "transactions",
  EVENTS: "/events",
  CONTENT: "/content",
  JOBS: "/jobs",
  BILLING: "/billing",
  REPORTS: "/reports",
  ADMIN: "/admin",
  PRODUCT_DASHBOARD: "product-dashboard",
  GENERAL_INFO: "general-info",
  PRICING: "pricing",
  FEATURE: "feature",
};
